version: '2'
services:
  prototype:
    build: .
    volumes:
#  - .:/app # . not working on windows - full path must be used
      - /c/Users/petea/DockerWorkspace/spring-boot-prototype:/prototype
    volumes_from:
      - gradledata
    working_dir: /prototype
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
      - mongodb
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: integ
  mongodb:
    image: mongo
    ports:
        - "27017:27017" 
    volumes_from:
        - mongodata
    restart: always
#mongoclient is not stable (use the local one or as a service version http://www.mongoclient.com:3000/)
  # mongoclient:
    # image: mongoclient/mongoclient:1.4.0
    # ports:
        # - "3000:3000"
    # depends_on:
      # - mongodb
  mysqldb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    #command: redis-server --requirepass redis --appendonly yes
    volumes_from:
      - redisdata
  nodered:
    #image: nodered/node-red-docker
    build: ./nodered
    ports:
      - "1880:1880"
    volumes_from:
      - nodereddata
    depends_on:
      - prototype
    environment:
      FLOWS: myFlows.json
      #NODE_OPTIONS: "--max_old_space_size=128"
  freeboard:
    build: ./freeboard
    ports:
      - "80:80"
#      volumes_from:
#        - freeboarddata
  gradledata:
    image: ubuntu
    volumes:
      - "/persistence/gradle:/root/.gradle/caches/"
    command: echo Data for GRADLE
  mongodata:
    image: ubuntu
    volumes:
      - "/persistence/mongodb:/data/db"
    command: echo Persistence for Mongo
  nodereddata:
    image: ubuntu
    volumes:
      - "/persistence/nodered:/data"
    command: echo Persistence for NodeRed
  redisdata:
    image: ubuntu
    volumes:
      - "/persistence/redis:/data"
    command: echo Persistence for Redis
  #  freeboarddata:
  #    image: ubuntu
  #    volumes:
  #      - "/persistence/freeboard:/data"
  #    command: echo Persistence for Freeboard