app:
 build: .
 volumes:
  - .:/app
 volumes_from:
  - gradledata
 working_dir: /app
 ports:
  - "8081:8081"
 links:
  - db
 environment:
  SPRING_PROFILES_ACTIVE: integ
db:
 image: mysql:5.6
 environment:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: TEST
gradledata:
 image: ubuntu
 volumes:
 #.gradle
  - "/root/.gradle"
 command: echo Data for GRADLE
