version: '2'
services:
  mongodb:
    image: mongo
    ports:
        - "27017:27017"
    volumes_from:
        - mongodata
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      #command: redis-server --requirepass redis --appendonly yes
    volumes_from:
        - redisdata
  redisdata:
      image: ubuntu
      volumes:
        - "/persistence/redis:/data"
      command: echo Persistence for Redis
  mongodata:
    image: ubuntu
    volumes:
      - "/persistence/mongodb:/data/db"
    command: echo Persistence for Mongo