app:
 build: .
 volumes:
#  - .:/app # . not working on windows - full path must be used
  - /c/Users/petea/DockerWorkspace/spring-boot-prototype:/app
 volumes_from:
  - gradledata
 working_dir: /app
 ports:
  - "8082:8082"
 links:
  - db
 environment:
  SPRING_PROFILES_ACTIVE: integ
db:
 image: mysql:5.6
 environment:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: test
gradledata:
 image: ubuntu
 volumes:
  - "/root/.gradle/caches/"
 command: echo Data for GRADLE