version: '2'
services:
  mongodb:
    image: mongo
    ports:
        - "27017:27017"
    volumes_from:
        - mongodata
    restart: always
  mongodata:
    image: ubuntu
    volumes:
      - "/persistence/mongodb:/data/db"
    command: echo Persistence for Mongo