version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    #command: redis-server --requirepass redis --appendonly yes
    volumes_from:
      - redisdata
  redisdata:
    image: ubuntu
    volumes:
      - "/persistence/redis:/data"
    command: echo Persistence for Redis