app:
 build: .
 volumes:
  - .:/app
 volumes_from:
  - gradle_data
 working_dir: /app
 ports:
  - "8080:8080"
 links:
  - db
 environment:
  SPRING_PROFILES_ACTIVE: nondev
db:
 image: mysql:5.6
 environment:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: TEST