spring:
    profiles: devh2
send:
   visitor: sergiu
   message: welcome ${send.visitor}. This is how boot works!
flyway:
   user: sa
   paswword: ""
   url: jdbc:h2:mem:testdb;TRACE_LEVEL_SYSTEM_OUT=1
#   url: jdbc:h2:mem:testdb;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=true;INIT=create schema if not exists public;TRACE_LEVEL_SYSTEM_OUT=1
#   url: jdbc:h2:file:///d:/Development/H2DB/db3;TRACE_LEVEL_SYSTEM_OUT=1
   baselineOnMigrate: true

---
spring:
    profiles: devmysql
send:
   visitor: sergiu
   message: welcome ${send.visitor}. This is how boot works!
flyway:
   user: root
   password: ""
   driver: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test
   baselineOnMigrate: true
jpa:
   bonecp:
      driverClass: com.mysql.jdbc.Driver
      maxConnectionsPerPartition: 20
      minConnectionsPerPartition: 10
      partitionCount: 3
      acquireIncrement: 10
      statementsCacheSize: 50
      releaseHelperThreads: 3
      acquireRetryAttempts: 0
      acquireRetryDelayInMs: 1000
      connectionTimeoutInMs: 3000
      master:
        jdbcUrl: jdbc:mysql://localhost:3306/test
        jdbcUsername: root
        jdbcPassword: ""
---
spring:
    profiles: integ
send:
   visitor: sergiu
   message: welcome ${send.visitor}. This is how boot works!
flyway:
   user: root
   password: password
   driver: com.mysql.jdbc.Driver
   url: jdbc:mysql://db:3306/test
   baselineOnMigrate: true
jpa:
   bonecp:
      driverClass: com.mysql.jdbc.Driver
      maxConnectionsPerPartition: 20
      minConnectionsPerPartition: 10
      partitionCount: 3
      acquireIncrement: 10
      statementsCacheSize: 50
      releaseHelperThreads: 3
      acquireRetryAttempts: 0
      acquireRetryDelayInMs: 1000
      connectionTimeoutInMs: 3000
      master:
        jdbcUrl: jdbc:mysql://db:3306/test
        jdbcUsername: root
        jdbcPassword: "password"
